import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Users,
  Building2,
  BookOpen,
  MessageSquareQuote,
  IndianRupee,
  FileText,
  Bell,
  Settings,
  Bus,
  ClipboardList,
  Clock,
  Star,
  User,
  Layers,
  HelpCircle,
  Tags,
  FolderOpen,
  TrendingUp,
  Briefcase,
  Heart,
  Wallet,
  Receipt,
  FileSignature,
  BadgePercent,
  Banknote,
  BarChart3,
  CalendarDays,
  ScrollText,
  Activity,
  UserCog,
  MapPinned,
} from "lucide-react";

export type PanelNavLink = { to: string; icon: LucideIcon; label: string };

export const adminPanelLinks: PanelNavLink[] = [
  { to: "/admin/dashboard", icon: LayoutDashboard, label: "Dashboard" },
  { to: "/admin/analytics", icon: BarChart3, label: "Analytics" },
  { to: "/admin/vendors", icon: Building2, label: "Vendors" },
  { to: "/admin/companies", icon: Briefcase, label: "B2B Companies" },
  { to: "/admin/customers", icon: Users, label: "Customers" },
  { to: "/admin/bookings", icon: BookOpen, label: "Bookings" },
  { to: "/admin/drivers", icon: UserCog, label: "Drivers" },
  { to: "/admin/calendar", icon: CalendarDays, label: "Calendar" },
  { to: "/admin/quotes", icon: MessageSquareQuote, label: "Quote Monitor" },
  { to: "/admin/payments", icon: IndianRupee, label: "Payments" },
  { to: "/admin/payouts", icon: Banknote, label: "Vendor Payouts" },
  { to: "/admin/offers", icon: BadgePercent, label: "Offers" },
  { to: "/admin/audit-logs", icon: ScrollText, label: "Audit Logs" },
  { to: "/admin/activity", icon: Activity, label: "Activity" },
  { to: "/admin/cms", icon: FileText, label: "Content Hub" },
  { to: "/admin/services", icon: Layers, label: "Services" },
  { to: "/admin/blogs", icon: BookOpen, label: "Blogs" },
  { to: "/admin/blog-categories", icon: FolderOpen, label: "Blog Categories" },
  { to: "/admin/blog-tags", icon: Tags, label: "Blog Tags" },
  { to: "/admin/vehicle-types", icon: Bus, label: "Vehicle Types" },
  { to: "/admin/faqs", icon: HelpCircle, label: "FAQs" },
  { to: "/admin/seo", icon: MapPinned, label: "SEO Manager" },
  { to: "/admin/notifications", icon: Bell, label: "Notifications" },
  { to: "/admin/settings", icon: Settings, label: "Settings" },
];

export const vendorPanelLinks: PanelNavLink[] = [
  { to: "/vendor/dashboard", icon: LayoutDashboard, label: "Dashboard" },
  { to: "/vendor/analytics", icon: TrendingUp, label: "Analytics" },
  { to: "/vendor/fleet", icon: Bus, label: "Fleet" },
  { to: "/vendor/drivers", icon: UserCog, label: "Drivers" },
  { to: "/vendor/calendar", icon: CalendarDays, label: "Calendar" },
  { to: "/vendor/leads", icon: ClipboardList, label: "Leads" },
  { to: "/vendor/quotes", icon: MessageSquareQuote, label: "Quotes" },
  { to: "/vendor/bookings", icon: BookOpen, label: "Bookings" },
  { to: "/vendor/documents", icon: FileText, label: "Documents" },
  { to: "/vendor/payments", icon: IndianRupee, label: "Payments" },
  { to: "/vendor/earnings", icon: IndianRupee, label: "Earnings" },
  { to: "/vendor/notifications", icon: Bell, label: "Notifications" },
  { to: "/vendor/profile", icon: User, label: "Profile" },
];

export const b2bPanelLinks: PanelNavLink[] = [
  { to: "/b2b/dashboard", icon: LayoutDashboard, label: "Dashboard" },
  { to: "/b2b/bookings", icon: BookOpen, label: "Bookings" },
  { to: "/b2b/trips", icon: Bus, label: "Trips" },
  { to: "/b2b/employees", icon: Users, label: "Employees" },
  { to: "/b2b/favourites", icon: Heart, label: "Favourites" },
  { to: "/b2b/wallet", icon: Wallet, label: "Wallet" },
  { to: "/b2b/invoices", icon: Receipt, label: "Invoices" },
  { to: "/b2b/contracts", icon: FileSignature, label: "Contracts" },
  { to: "/b2b/payments", icon: IndianRupee, label: "Payments" },
];

export const customerPanelLinks: PanelNavLink[] = [
  { to: "/customer/dashboard", icon: LayoutDashboard, label: "Dashboard" },
  { to: "/customer/bookings", icon: BookOpen, label: "My Bookings" },
  { to: "/customer/quotes", icon: Clock, label: "My Quotes" },
  { to: "/customer/wishlist", icon: Heart, label: "Wishlist" },
  { to: "/customer/saved-trips", icon: MapPinned, label: "Saved Trips" },
  { to: "/customer/reviews", icon: Star, label: "Reviews" },
  { to: "/customer/profile", icon: User, label: "Profile" },
];
