/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusTypesForHireRouteImport } from './routes/bus-types-for-hire'
import { Route as BusTypesRouteImport } from './routes/bus-types'
import { Route as BusRentalGuidesRouteImport } from './routes/bus-rental-guides'
import { Route as BusRentalRouteImport } from './routes/bus-rental'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SeoSlugRouteImport } from './routes/$seoSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorRegisterRouteImport } from './routes/vendor.register'
import { Route as VendorQuotesRouteImport } from './routes/vendor.quotes'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorLoginRouteImport } from './routes/vendor.login'
import { Route as VendorLeadsRouteImport } from './routes/vendor.leads'
import { Route as VendorFleetRouteImport } from './routes/vendor.fleet'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorBookingsRouteImport } from './routes/vendor.bookings'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as ServiceCityCitySlugRouteImport } from './routes/service-city.$citySlug'
import { Route as PoliciesRefundCancellationRouteImport } from './routes/policies.refund-cancellation'
import { Route as CustomerReviewsRouteImport } from './routes/customer.reviews'
import { Route as CustomerQuotesRouteImport } from './routes/customer.quotes'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerBookingsRouteImport } from './routes/customer.bookings'
import { Route as BusRentalCitySlugRouteImport } from './routes/bus-rental.$citySlug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as SeoSlugBusTypeSlugRouteImport } from './routes/$seoSlug.$busTypeSlug'
import { Route as SeoSlugRentalBusTypeSlugRouteImport } from './routes/$seoSlug.rental.$busTypeSlug'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusTypesForHireRoute = BusTypesForHireRouteImport.update({
  id: '/bus-types-for-hire',
  path: '/bus-types-for-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const BusTypesRoute = BusTypesRouteImport.update({
  id: '/bus-types',
  path: '/bus-types',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRentalGuidesRoute = BusRentalGuidesRouteImport.update({
  id: '/bus-rental-guides',
  path: '/bus-rental-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRentalRoute = BusRentalRouteImport.update({
  id: '/bus-rental',
  path: '/bus-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSlugRoute = SeoSlugRouteImport.update({
  id: '/$seoSlug',
  path: '/$seoSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => VendorRoute,
} as any)
const VendorQuotesRoute = VendorQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => VendorRoute,
} as any)
const VendorLeadsRoute = VendorLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => VendorRoute,
} as any)
const VendorFleetRoute = VendorFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => VendorRoute,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const VendorBookingsRoute = VendorBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => VendorRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCityCitySlugRoute = ServiceCityCitySlugRouteImport.update({
  id: '/service-city/$citySlug',
  path: '/service-city/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundCancellationRoute =
  PoliciesRefundCancellationRouteImport.update({
    id: '/policies/refund-cancellation',
    path: '/policies/refund-cancellation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerReviewsRoute = CustomerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerQuotesRoute = CustomerQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const BusRentalCitySlugRoute = BusRentalCitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => BusRentalRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const SeoSlugBusTypeSlugRoute = SeoSlugBusTypeSlugRouteImport.update({
  id: '/$busTypeSlug',
  path: '/$busTypeSlug',
  getParentRoute: () => SeoSlugRoute,
} as any)
const SeoSlugRentalBusTypeSlugRoute =
  SeoSlugRentalBusTypeSlugRouteImport.update({
    id: '/rental/$busTypeSlug',
    path: '/rental/$busTypeSlug',
    getParentRoute: () => SeoSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/bus-rental': typeof BusRentalRouteWithChildren
  '/bus-rental-guides': typeof BusRentalGuidesRoute
  '/bus-types': typeof BusTypesRoute
  '/bus-types-for-hire': typeof BusTypesForHireRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/routes': typeof RoutesRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/$seoSlug/$busTypeSlug': typeof SeoSlugBusTypeSlugRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bus-rental/$citySlug': typeof BusRentalCitySlugRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/policies/refund-cancellation': typeof PoliciesRefundCancellationRoute
  '/service-city/$citySlug': typeof ServiceCityCitySlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/fleet': typeof VendorFleetRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/$seoSlug/rental/$busTypeSlug': typeof SeoSlugRentalBusTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/bus-rental': typeof BusRentalRouteWithChildren
  '/bus-rental-guides': typeof BusRentalGuidesRoute
  '/bus-types': typeof BusTypesRoute
  '/bus-types-for-hire': typeof BusTypesForHireRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/routes': typeof RoutesRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/$seoSlug/$busTypeSlug': typeof SeoSlugBusTypeSlugRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bus-rental/$citySlug': typeof BusRentalCitySlugRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/policies/refund-cancellation': typeof PoliciesRefundCancellationRoute
  '/service-city/$citySlug': typeof ServiceCityCitySlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/fleet': typeof VendorFleetRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/$seoSlug/rental/$busTypeSlug': typeof SeoSlugRentalBusTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/bus-rental': typeof BusRentalRouteWithChildren
  '/bus-rental-guides': typeof BusRentalGuidesRoute
  '/bus-types': typeof BusTypesRoute
  '/bus-types-for-hire': typeof BusTypesForHireRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/routes': typeof RoutesRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/$seoSlug/$busTypeSlug': typeof SeoSlugBusTypeSlugRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bus-rental/$citySlug': typeof BusRentalCitySlugRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/policies/refund-cancellation': typeof PoliciesRefundCancellationRoute
  '/service-city/$citySlug': typeof ServiceCityCitySlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/vendor/bookings': typeof VendorBookingsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/fleet': typeof VendorFleetRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendor/register': typeof VendorRegisterRoute
  '/$seoSlug/rental/$busTypeSlug': typeof SeoSlugRentalBusTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/bus-rental'
    | '/bus-rental-guides'
    | '/bus-types'
    | '/bus-types-for-hire'
    | '/contact'
    | '/customer'
    | '/guides'
    | '/login'
    | '/routes'
    | '/signup'
    | '/vendor'
    | '/$seoSlug/$busTypeSlug'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vendors'
    | '/blog/$slug'
    | '/bus-rental/$citySlug'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/reviews'
    | '/policies/refund-cancellation'
    | '/service-city/$citySlug'
    | '/services/$serviceSlug'
    | '/vendor/bookings'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/fleet'
    | '/vendor/leads'
    | '/vendor/login'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendor/register'
    | '/$seoSlug/rental/$busTypeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/bus-rental'
    | '/bus-rental-guides'
    | '/bus-types'
    | '/bus-types-for-hire'
    | '/contact'
    | '/customer'
    | '/guides'
    | '/login'
    | '/routes'
    | '/signup'
    | '/vendor'
    | '/$seoSlug/$busTypeSlug'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vendors'
    | '/blog/$slug'
    | '/bus-rental/$citySlug'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/reviews'
    | '/policies/refund-cancellation'
    | '/service-city/$citySlug'
    | '/services/$serviceSlug'
    | '/vendor/bookings'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/fleet'
    | '/vendor/leads'
    | '/vendor/login'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendor/register'
    | '/$seoSlug/rental/$busTypeSlug'
  id:
    | '__root__'
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/book'
    | '/bus-rental'
    | '/bus-rental-guides'
    | '/bus-types'
    | '/bus-types-for-hire'
    | '/contact'
    | '/customer'
    | '/guides'
    | '/login'
    | '/routes'
    | '/signup'
    | '/vendor'
    | '/$seoSlug/$busTypeSlug'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vendors'
    | '/blog/$slug'
    | '/bus-rental/$citySlug'
    | '/customer/bookings'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/profile'
    | '/customer/quotes'
    | '/customer/reviews'
    | '/policies/refund-cancellation'
    | '/service-city/$citySlug'
    | '/services/$serviceSlug'
    | '/vendor/bookings'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/fleet'
    | '/vendor/leads'
    | '/vendor/login'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendor/register'
    | '/$seoSlug/rental/$busTypeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeoSlugRoute: typeof SeoSlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRoute
  BusRentalRoute: typeof BusRentalRouteWithChildren
  BusRentalGuidesRoute: typeof BusRentalGuidesRoute
  BusTypesRoute: typeof BusTypesRoute
  BusTypesForHireRoute: typeof BusTypesForHireRoute
  ContactRoute: typeof ContactRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  RoutesRoute: typeof RoutesRoute
  SignupRoute: typeof SignupRoute
  VendorRoute: typeof VendorRouteWithChildren
  PoliciesRefundCancellationRoute: typeof PoliciesRefundCancellationRoute
  ServiceCityCitySlugRoute: typeof ServiceCityCitySlugRoute
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-types-for-hire': {
      id: '/bus-types-for-hire'
      path: '/bus-types-for-hire'
      fullPath: '/bus-types-for-hire'
      preLoaderRoute: typeof BusTypesForHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-types': {
      id: '/bus-types'
      path: '/bus-types'
      fullPath: '/bus-types'
      preLoaderRoute: typeof BusTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-rental-guides': {
      id: '/bus-rental-guides'
      path: '/bus-rental-guides'
      fullPath: '/bus-rental-guides'
      preLoaderRoute: typeof BusRentalGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-rental': {
      id: '/bus-rental'
      path: '/bus-rental'
      fullPath: '/bus-rental'
      preLoaderRoute: typeof BusRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seoSlug': {
      id: '/$seoSlug'
      path: '/$seoSlug'
      fullPath: '/$seoSlug'
      preLoaderRoute: typeof SeoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/register': {
      id: '/vendor/register'
      path: '/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/quotes': {
      id: '/vendor/quotes'
      path: '/quotes'
      fullPath: '/vendor/quotes'
      preLoaderRoute: typeof VendorQuotesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/login': {
      id: '/vendor/login'
      path: '/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/leads': {
      id: '/vendor/leads'
      path: '/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof VendorLeadsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/fleet': {
      id: '/vendor/fleet'
      path: '/fleet'
      fullPath: '/vendor/fleet'
      preLoaderRoute: typeof VendorFleetRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/bookings': {
      id: '/vendor/bookings'
      path: '/bookings'
      fullPath: '/vendor/bookings'
      preLoaderRoute: typeof VendorBookingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-city/$citySlug': {
      id: '/service-city/$citySlug'
      path: '/service-city/$citySlug'
      fullPath: '/service-city/$citySlug'
      preLoaderRoute: typeof ServiceCityCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refund-cancellation': {
      id: '/policies/refund-cancellation'
      path: '/policies/refund-cancellation'
      fullPath: '/policies/refund-cancellation'
      preLoaderRoute: typeof PoliciesRefundCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/reviews': {
      id: '/customer/reviews'
      path: '/reviews'
      fullPath: '/customer/reviews'
      preLoaderRoute: typeof CustomerReviewsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/quotes': {
      id: '/customer/quotes'
      path: '/quotes'
      fullPath: '/customer/quotes'
      preLoaderRoute: typeof CustomerQuotesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/bus-rental/$citySlug': {
      id: '/bus-rental/$citySlug'
      path: '/$citySlug'
      fullPath: '/bus-rental/$citySlug'
      preLoaderRoute: typeof BusRentalCitySlugRouteImport
      parentRoute: typeof BusRentalRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$seoSlug/$busTypeSlug': {
      id: '/$seoSlug/$busTypeSlug'
      path: '/$busTypeSlug'
      fullPath: '/$seoSlug/$busTypeSlug'
      preLoaderRoute: typeof SeoSlugBusTypeSlugRouteImport
      parentRoute: typeof SeoSlugRoute
    }
    '/$seoSlug/rental/$busTypeSlug': {
      id: '/$seoSlug/rental/$busTypeSlug'
      path: '/rental/$busTypeSlug'
      fullPath: '/$seoSlug/rental/$busTypeSlug'
      preLoaderRoute: typeof SeoSlugRentalBusTypeSlugRouteImport
      parentRoute: typeof SeoSlugRoute
    }
  }
}

interface SeoSlugRouteChildren {
  SeoSlugBusTypeSlugRoute: typeof SeoSlugBusTypeSlugRoute
  SeoSlugRentalBusTypeSlugRoute: typeof SeoSlugRentalBusTypeSlugRoute
}

const SeoSlugRouteChildren: SeoSlugRouteChildren = {
  SeoSlugBusTypeSlugRoute: SeoSlugBusTypeSlugRoute,
  SeoSlugRentalBusTypeSlugRoute: SeoSlugRentalBusTypeSlugRoute,
}

const SeoSlugRouteWithChildren =
  SeoSlugRoute._addFileChildren(SeoSlugRouteChildren)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BusRentalRouteChildren {
  BusRentalCitySlugRoute: typeof BusRentalCitySlugRoute
}

const BusRentalRouteChildren: BusRentalRouteChildren = {
  BusRentalCitySlugRoute: BusRentalCitySlugRoute,
}

const BusRentalRouteWithChildren = BusRentalRoute._addFileChildren(
  BusRentalRouteChildren,
)

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerQuotesRoute: typeof CustomerQuotesRoute
  CustomerReviewsRoute: typeof CustomerReviewsRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerQuotesRoute: CustomerQuotesRoute,
  CustomerReviewsRoute: CustomerReviewsRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface VendorRouteChildren {
  VendorBookingsRoute: typeof VendorBookingsRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorFleetRoute: typeof VendorFleetRoute
  VendorLeadsRoute: typeof VendorLeadsRoute
  VendorLoginRoute: typeof VendorLoginRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorQuotesRoute: typeof VendorQuotesRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorBookingsRoute: VendorBookingsRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorFleetRoute: VendorFleetRoute,
  VendorLeadsRoute: VendorLeadsRoute,
  VendorLoginRoute: VendorLoginRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorQuotesRoute: VendorQuotesRoute,
  VendorRegisterRoute: VendorRegisterRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeoSlugRoute: SeoSlugRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRoute,
  BusRentalRoute: BusRentalRouteWithChildren,
  BusRentalGuidesRoute: BusRentalGuidesRoute,
  BusTypesRoute: BusTypesRoute,
  BusTypesForHireRoute: BusTypesForHireRoute,
  ContactRoute: ContactRoute,
  CustomerRoute: CustomerRouteWithChildren,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  RoutesRoute: RoutesRoute,
  SignupRoute: SignupRoute,
  VendorRoute: VendorRouteWithChildren,
  PoliciesRefundCancellationRoute: PoliciesRefundCancellationRoute,
  ServiceCityCitySlugRoute: ServiceCityCitySlugRoute,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
